config/routes.rb
Rails.application.routes.draw do
  resources :messages
  resources :rooms
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  resources :matches
  resources :mentees
  resources :mentors
  resources :users
  resources :states, only: :index
  root 'matches#home'
  get '/room', to: 'rooms#index'
  post 'room/create', to: 'rooms#create'
  get  '/signup',  to: 'users#new'
  get  '/channelshow',  to: 'channnel_users#show'
  post 'channel_users/create'
  get  '/home',  to: 'matches#home'
  get '/menteeprofile/:id', to: 'mentees#show', as: 'menteeprofile'
  get '/mentorprofile/:id', to: 'mentors#show', as: 'mentorprofile'
  get '/userprofile/:id', to: 'users#show', as: 'userprofile'
  get    '/login',   to: 'sessions#new'
  get    '/explore',   to: 'welcome#show'
  get     '/additional-info', to: 'users#additional_info'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  post 'matches/create'
  post 'welcome/accept', to: 'welcome#accept'  #for rejecting matches
  post 'welcome/reject', to: 'welcome#reject'    #for accepting matches
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/mentee.rb
class Mentee < ApplicationRecord
    has_many :matches
    has_many :mentors, through: :matches
    has_one_attached :avatar
    validates :major, presence: true
    validates :length_of_mentorship, presence: true

    def majors
        subjects_hash = {}
        count = 0
        subject_list = JSON.parse(File.read('./db/subject.json'))
        subject_list.each do |subject|
            subjects_hash[subject["id"]] = subject["name"]
        end
        return subjects_hash
    end

end

app/controllers/mentees_controller.rb
class MenteesController < ApplicationController
  before_action :set_mentee, only: %i[ show edit update destroy ]
  # GET /mentees or /mentees.json
  require 'matches_controller.rb'
  def index
    @mentees = Mentee.all
  end

  # GET /mentees/1 or /mentees/1.json
  def show
    @user = current_user
  end

  # GET /mentees/new
  def new
    @mentee = Mentee.new
  end

  # GET /mentees/1/edit
  def edit
  end

  # POST /mentees or /mentees.json
  def create
    @mentee = Mentee.new(mentee_params)
    @users=User.all
    @user=@users.last
    @mentee[:user_id] = @user.id
    if @mentee.save
      if current_user.mentor && current_user.mentee
        @mentor = Mentor.new()
        render 'additional_mentor'
      else
        redirect_to home_path
      end
    end
  end

  # PATCH/PUT /mentees/1 or /mentees/1.json
  def update
    respond_to do |format|
      if @mentee.update(mentee_params)
        format.html { redirect_to @mentee, notice: "Mentee was successfully updated." }
        format.json { render :show, status: :ok, location: @mentee }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @mentee.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /mentees/1 or /mentees/1.json
  def destroy
    @mentee.destroy
    respond_to do |format|
      format.html { redirect_to mentees_url, notice: "Mentee was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_mentee
      @mentee = Mentee.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def mentee_params
      params.require(:mentee).permit(:user_id,:major, :area_of_interest, :preferred_method_of_contact, :location, :length_of_mentorship, :graduation_year, :avatar)
    end
end

app/helpers/mentees_helper.rb
module MenteesHelper
end

app/views/mentees/_form.html.erb
<div class="row center">
  <div class="col-md-6 col-md-offset-3">
<%= form_with(model: mentee) do |form| %>
  <% if mentee.errors.any? %>
    <div id=“error_explanation”>
      <h2><%= pluralize(mentee.errors.count, “error”) %> prohibited this mentee from being saved:</h2>
      <ul>
        <% mentee.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
    <%= form.label :major %>
    <%= form.text_field :major %>

    <%= form.label :area_of_interest %>
    <%= form.text_field :area_of_interest %>

    <%= form.label :preferred_method_of_contact %>
    <%= form.text_field :preferred_method_of_contact %>

    <%= form.label :location %>
    <%= form.text_field :location %>

    <%= form.label :length_of_mentorship %>
    <%= form.number_field :length_of_mentorship %>

    <%= form.label :graduation_year %>
    <%= form.text_field :graduation_year %>
    
    <%= form.label "Profile Photo" %>
    <%= form.file_field :avatar %>

  <div class=“actions”>
    <%= form.submit %>
  </div>
<% end %>
</div>
</div>

app/views/mentees/_mentor_form.html.erb
<%= form_with(model: mentor) do |form| %>
  <% if mentor.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(mentor.errors.count, "error") %> prohibited this mentee from being saved:</h2>

      <ul>
        <% mentor.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :area_of_expertise %>
    <%= form.text_field :area_of_expertise, class: 'mb-1 form-control' %>
  </div>

  <div class="field">
    <%= form.label :preferred_method_of_contact, "preferred Method of Contact" %>
    <%= form.text_field :preferred_method_of_contact, class: 'mb-1 form-control' %>
  </div>

  <div class="field">
    <%= form.label :school, "Current School or Alma Mater" %>
    <%= form.text_field :school, class: 'mb-1 form-control' %>
  </div>

  <div class="field">
    <%= form.label :current_position %>
    <%= form.text_field :current_position, class: 'mb-1 form-control' %>
  </div>

  <div class="field">
    <%= form.label :length_of_mentorship, "Length of mentorship desired (in weeks)" %>
    <%= form.number_field :length_of_mentorship, class: 'mb-1 form-control' %>
  </div>

  <div class="field">
    <%= form.label :location %>
    <%= form.text_field :location, class: 'mb-1 form-control' %>
  </div>

  <div class="actions">
    <%= form.submit "Create account" %>
  </div>
<% end %>

app/views/mentees/additional_mentor.html.erb
<h1>New Mentor</h1>
<%= render 'mentor_form', mentor: @mentor %>

<%= link_to 'Back', users_path %>

app/views/mentees/edit.html.erb
 <div class= "center jumbotron" style="background:white" >


<h1 style="align:left">Edit Profile</h1>

<%= render 'form', mentee: @mentee %>

<%= link_to 'Go to Profile', menteeprofile_path(@mentee) %>
</div>
</div>

app/views/mentees/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Mentees</h1>

<table>
  <thead>
    <tr>
      <th>Major</th>
      <th>Area of interest</th>
      <th>preferred method of contact</th>
      <th>Location</th>
      <th>Length of mentorship</th>
      <th>Graduation year</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @mentees.each do |mentee| %>
      <tr>
        <td><%= mentee.major %></td>
        <td><%= mentee.area_of_interest %></td>
        <td><%= mentee.preferred_method_of_contact %></td>
        <td><%= mentee.location %></td>
        <td><%= mentee.length_of_mentorship %></td>
        <td><%= mentee.graduation_year %></td>
        <td><%= link_to 'Show', mentee %></td>
        <td><%= link_to 'Edit', edit_mentee_path(mentee) %></td>
        <td><%= link_to 'Destroy', mentee, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Mentee', new_mentee_path %>

app/views/mentees/new.html.erb
<h1>New Mentee</h1>

<%= render 'form', mentee: @mentee %>

<%= link_to 'Back', mentees_path %>

app/views/mentees/show.html.erb
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
</head>
<body>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
<div class= "center jumbotron emp-profile" style="box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2);">
            <form method="post">
                <div class="row">
                    <div class="col-md-6">
                        <div class="profile-head">
                                    <h1>
                                        <%= @user.firstname + " " + @user.lastname %>
                                    </h1>
                                    <h6>
                                        Seeking Mentorship
                                    </h6>
                            <br>
                            <br>
                            <ul class="nav nav-tabs" id="myTab" role="tablist">
                                <li class="nav-item active">
                                    <a class="nav-link active" id="home-tab" data-toggle="tab" href="#home" role="tab" aria-controls="home" aria-selected="true">About</a>
                                </li>
                            </ul>
                        </div>
                        <div class="tab-content" id="myTabContent">
                            <div class="tab-pane active" class="fade show" id="home" role="tabpanel" aria-labelledby="home-tab">
                                <table class= "table">
                                      <tr>
                                        <th>Major</th>
                                        <td><%= @mentee.major %></td>
                                      </tr>
                                      <tr>
                                        <th>Areas of Interest</th>
                                        <td><%= @mentee.area_of_interest%></td>
                                      </tr>
                                      <tr>
                                        <th>Location</th>
                                        <td><%= @mentee.location %></td>
                                      </tr>
                                      <tr>
                                        <th>Graduation Year</th>
                                        <td><%= @mentee.graduation_year %></td>
                                      </tr>
                                      </tr>
                                        <th>Preferred Method of Contact</th>
                                        <td><%= @mentee.preferred_method_of_contact %></td>
                                      <tr>
                                      </tr>
                                        <th>Preferred Length of Mentorship in Weeks</th>
                                        <td><%= @mentee.length_of_mentorship %></td>
                                      <tr>
                                        <th colspan="20"></th>
                                      </tr>
                                  </table>
                            </div>
                            <div class="tab-pane fade" id="profile" role="tabpanel" aria-labelledby="profile-tab">
                                        <h2>More Details Will be Added</h2>
                            </div>
                        </div>
                    </div>
                      <div class="col-md-6">
                        <div class="profile-img">
                        <% if @mentee.avatar.attached? %>
                          <img src="<%=(url_for(@mentee.avatar))%>" width="220" height="200">
                        <% else %>
                            <img src="https://www.pngitem.com/pimgs/m/30-307416_profile-icon-png-image-free-download-searchpng-employee.png" alt="" style= "align:right" width="220" height="200"/>
                        <% end %>
                        </div>
                        <br>
                        <%= link_to 'Edit Profile', edit_mentee_path(@mentee), class: "button2" %>
                    </div>
                    </div>
                </div>
            </form>           
        </div>

    </body>
    </html>