config/routes.rb
Rails.application.routes.draw do
  resources :messages
  resources :rooms
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  resources :matches
  resources :mentees
  resources :mentors
  resources :users
  resources :states, only: :index
  root 'matches#home'
  get '/room', to: 'rooms#index'
  post 'room/create', to: 'rooms#create'
  get  '/signup',  to: 'users#new'
  get  '/channelshow',  to: 'channnel_users#show'
  post 'channel_users/create'
  get  '/home',  to: 'matches#home'
  get '/menteeprofile/:id', to: 'mentees#show', as: 'menteeprofile'
  get '/mentorprofile/:id', to: 'mentors#show', as: 'mentorprofile'
  get '/userprofile/:id', to: 'users#show', as: 'userprofile'
  get    '/login',   to: 'sessions#new'
  get    '/explore',   to: 'welcome#show'
  get     '/additional-info', to: 'users#additional_info'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  post 'matches/create'
  post 'welcome/accept', to: 'welcome#accept'  #for rejecting matches
  post 'welcome/reject', to: 'welcome#reject'    #for accepting matches
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/mentor.rb
class Mentor < ApplicationRecord
    has_many :matches
    has_many :mentees, through: :matches
    has_one_attached :avatar
    validates :current_position, presence: true 
    validates :length_of_mentorship, presence: true

    def get_full_jobs
        return Profession::Profession.list
    end

    def search_by_term(search_term)
        return Profession::Profession.match(search_term)
    end
end

app/controllers/mentors_controller.rb
class MentorsController < ApplicationController
  before_action :set_mentor, only: %i[ show edit update destroy ]

  # GET /mentors or /mentors.json
  def index
    @mentors = Mentor.all
  end

  # GET /mentors/1 or /mentors/1.json
  def show
    @user = current_user
  end

  # GET /mentors/new
  def new
    @mentor = Mentor.new
  end

  # GET /mentors/1/edit
  def edit
  end

  # POST /mentors or /mentors.json
  def create
    @mentor = Mentor.new(mentor_params)
    @users = User.all
    @user = @users.last
    @mentor[:user_id] = @user.id
    if @mentor.save
      redirect_to home_path
    end
  end

  # PATCH/PUT /mentors/1 or /mentors/1.json
  def update
    respond_to do |format|
      if @mentor.update(mentor_params)
        format.html { redirect_to @mentor, notice: "Mentor was successfully updated." }
        format.json { render :show, status: :ok, location: @mentor }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @mentor.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /mentors/1 or /mentors/1.json
  def destroy
    @mentor.destroy
    respond_to do |format|
      format.html { redirect_to mentors_url, notice: "Mentor was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_mentor
      @mentor = Mentor.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def mentor_params
      params.require(:mentor).permit(:user_id, :area_of_expertise, :preferred_method_of_contact, :school, :current_position, :location, :length_of_mentorship, :avatar)
    end
end

app/helpers/mentors_helper.rb
module MentorsHelper
end

app/views/mentors/_form.html.erb
<%= form_with(model: mentor) do |form| %>
  <% if mentor.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(mentor.errors.count, "error") %> prohibited this mentor from being saved:</h2>
      <ul>
        <% mentor.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

    <%= form.label :area_of_expertise %>
    <%= form.text_field :area_of_expertise %>

    <%= form.label :preferred_method_of_contact %>
    <%= form.text_field :preferred_method_of_contact %>

    <%= form.label :school %>
    <%= form.text_field :school %>

    <%= form.label :current_position %>
    <%= form.text_field :current_position %>

    <%= form.label :location %>
    <%= form.text_field :location %>

    <%= form.label :length_of_mentorship %>
    <%= form.number_field :length_of_mentorship %>

    <%= form.label "Profile Photo" %>
    <%= form.file_field :avatar %>

    <%= form.submit %>
<% end %>

app/views/mentors/edit.html.erb
<h1 style="align:left">Edit Profile</h1>

<%= render 'form', mentor: @mentor %>

<%= link_to 'Show', mentorprofile_path(@mentor) %> |

app/views/mentors/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Mentors</h1>

<table>
  <thead>
    <tr>
      <th>Area of expertise</th>
      <th>Preferred method of contact</th>
      <th>School</th>
      <th>Current position</th>
      <th>Location</th>
      <th>Length of mentorship</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @mentors.each do |mentor| %>
      <tr>
        <td><%= mentor.area_of_expertise %></td>
        <td><%= mentor.preferred_method_of_contact %></td>
        <td><%= mentor.school %></td>
        <td><%= mentor.current_position %></td>
        <td><%= mentor.location %></td>
        <td><%= mentor.length_of_mentorship %></td>
        <td><%= link_to 'Show', mentor %></td>
        <td><%= link_to 'Edit', edit_mentor_path(mentor) %></td>
        <td><%= link_to 'Destroy', mentor, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Mentor', new_mentor_path %>

app/views/mentors/new.html.erb
<h1>New Mentor</h1>

<%= render 'form', mentor: @mentor %>

<%= link_to 'Back', mentors_path %>

app/views/mentors/show.html.erb
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
</head>
<body>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
<div class= "center jumbotron emp-profile" style="box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2);">
            <form method="post">
                <div class="row">
                    <div class="col-md-6">
                        <div class="profile-head">
                                    <h1>
                                        <%= @user.firstname + " " + @user.lastname %>
                                    </h1>
                                    <h6>
                                        Mentor
                                    </h6>
                            <br>
                            <br>
                            <ul class="nav nav-tabs" id="myTab" role="tablist">
                                <li class="nav-item active">
                                    <a class="nav-link active" id="home-tab" data-toggle="tab" href="#home" role="tab" aria-controls="home" aria-selected="true">About</a>
                                </li>
                            </ul>
                        </div>
                        <div class="tab-content" id="myTabContent">
                            <div class="tab-pane active" class="fade show" id="home" role="tabpanel" aria-labelledby="home-tab">
                                <table class= "table">
                                      <tr>
                                        <th>Area of expertise</th>
                                        <td><%= @mentor.area_of_expertise %></td>
                                      </tr>
                                      <tr>
                                        <th>Preferred method of contact</th>
                                        <td><%= @mentor.preferred_method_of_contact%></td>
                                      </tr>
                                      <tr>
                                        <th>University</th>
                                        <td><%= @mentor.school %></td>
                                      </tr>
                                      <tr>
                                        <th>Current position</th>
                                        <td><%= @mentor.current_position %></td>
                                      </tr>
                                      </tr>
                                        <th>Location</th>
                                        <td><%= @mentor.location %></td>
                                      <tr>
                                      </tr>
                                        <th>Preferred Length of Mentorship in Weeks</th>
                                        <td><%= @mentor.length_of_mentorship %></td>
                                      <tr>
                                        <th colspan="20"></th>
                                      </tr>
                                  </table>
                            </div>
                        </div>
                    </div>
                      <div class="col-md-6">
                        <div class="profile-img">
                        <% if @mentor.avatar.attached? %>
                          <img src="<%=(url_for(@mentor.avatar))%>" width="220" height="200">
                        <% else %>
                            <img src="https://www.pngitem.com/pimgs/m/30-307416_profile-icon-png-image-free-download-searchpng-employee.png" alt="" style= "align:right" width="220" height="200"/>
                        <% end %>
                            <%# <div class="file btn btn-lg btn-primary">
                                Change Photo
                                <input type="file" name="file"/>
                            </div> %>
                        </div>
                        <%= link_to 'Edit Profile', edit_mentor_path(@mentor), class: "button2" %>
                    </div>
                    </div>
                </div>
            </form>           
        </div>

    </body>
    </html>