config/routes.rb
Rails.application.routes.draw do
  resources :messages
  resources :rooms
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  resources :matches
  resources :mentees
  resources :mentors
  resources :users
  resources :states, only: :index
  root 'matches#home'
  get '/room', to: 'rooms#index'
  post 'room/create', to: 'rooms#create'
  get  '/signup',  to: 'users#new'
  get  '/channelshow',  to: 'channnel_users#show'
  post 'channel_users/create'
  get  '/home',  to: 'matches#home'
  get '/menteeprofile/:id', to: 'mentees#show', as: 'menteeprofile'
  get '/mentorprofile/:id', to: 'mentors#show', as: 'mentorprofile'
  get '/userprofile/:id', to: 'users#show', as: 'userprofile'
  get    '/login',   to: 'sessions#new'
  get    '/explore',   to: 'welcome#show'
  get     '/additional-info', to: 'users#additional_info'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  post 'matches/create'
  post 'welcome/accept', to: 'welcome#accept'  #for rejecting matches
  post 'welcome/reject', to: 'welcome#reject'    #for accepting matches
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/match.rb
class Match < ApplicationRecord
   belongs_to :mentee
   belongs_to :mentor

   #accepts a match
    def accept(accepted,other_match)
        puts "in accept"
        puts other_match.id
        if self.update_attribute(:accepted, accepted)
            puts "Success! accepted"
        else
           puts "Failed to update record. Handle the error."
        end
        puts "see this b"
        ApplicationController.helpers.update_match(other_match.user_id, other_match)
    end

    #rejects a match
    def reject(rejected)
      if self.update_attribute(:rejected, rejected)
          puts "Success! rejected"
      else
         puts "Failed to update record. Handle the error."
      end
  end


  def get_full_jobs
   return Profession::Profession.list
  end
 
   
end
 




  

app/controllers/matches_controller.rb
require_relative "job_map.rb"
class MatchesController < ApplicationController
  # include CableReady::Broadcaster   #not yet implemented
  before_action :set_match, only: %i[ show edit update destroy ]

  @@matches_hash = {}
  # GET /mentors or /mentors.json
  def index
    @user = current_user
    @all_matches = Match.all
    @mentors = Mentor.all
    @mentees=Mentee.all
    @users=User.all
    @matches_for_user = @@matches_hash
    @match=Match.first
    if @user.mentee?
      @temp_id = Mentee.find_by(user_id: @user.id).id
    end
    if @user.mentor?
      @temp_id = Mentor.find_by(user_id: @user.id).id
    end
  end

  def home
    @all_matches = Match.all
    @mentors = Mentor.all
    @mentees=Mentee.all
    @users=User.all
    @matches_for_user = @@matches_hash
    @match=Match.first
  end


  # GET /mentors/new
  def new
    @match = Match.new
  end

  # GET /mentors/1/edit
  def edit
  end

  #user is mentor : identifier 0 mentee : identifier 1 both : identifier 2
  def check_duplicate(identifier)
    duplicate = false
    matches = Match.all
    matches.each do |match|
      if match.user_id == @newMatch.user_id && match.mentor_id == @newMatch.mentor_id && match.mentee_id == @newMatch.mentee_id
        duplicate = true
      end
    end
    if duplicate == false
      @newMatch.save
      if identifier == 0    #need a mentee record
        make_mentee_match()
      elsif identifier == 1   #need a mentor record
        make_mentor_match()
      end
    end
    @matches_arr.push(@newMatch)
  end

  def make_mentee_match()
    @users = User.all
    @other_party = @mentees.find_by(id: @newMatch.mentee_id)
    other_party_user_id = @other_party.user_id
    other_user = @users.find_by(id: other_party_user_id)
    @otherMatch= Match.new(:user_id => other_party_user_id, :mentor_id => @newMatch.mentor_id, :mentee_id => @newMatch.mentee_id, :accepted => false, :rejected => false)    #creates the other match
    @otherMatch.save
    @test_party = @mentors.find_by(id: @newMatch.mentor_id)
  end

  def make_mentor_match()
    @users = User.all
    @other_party = @mentors.find_by(id: @newMatch.mentor_id)
    other_party_user_id = @other_party.user_id
    other_user = @users.find_by(id: other_party_user_id)
    @otherMatch= Match.new(:user_id => other_party_user_id, :mentor_id => @newMatch.mentor_id, :mentee_id => @newMatch.mentee_id, :accepted => false, :rejected => false)    #creates the other match
    @otherMatch.save
    @test_party = @mentees.find_by(id: @newMatch.mentee_id)
  end

  def is_mentor()
    @mentor = Mentor.find_by(user_id: current_user.id)
      @mentees.each do |mentee|
        if mentee.user_id != @mentor.user_id
          if (@common_subjects_map[mentee.major]) != nil    #if theres a record in map for particular job/major
            if @mentor.length_of_mentorship==mentee.length_of_mentorship or (@common_subjects_map[mentee.major].include? @mentor.current_position)
              @newMatch= Match.new(:user_id => current_user.id, :mentor_id => @mentor.id, :mentee_id => mentee.id, :accepted => false, :rejected => false)
              check_duplicate(0)
            end
          else
            if @mentor.length_of_mentorship==mentee.length_of_mentorship 
              @newMatch= Match.new(:user_id => current_user.id, :mentor_id => @mentor.id, :mentee_id => mentee.id, :accepted => false, :rejected => false)
              check_duplicate(0)
            end
          end
        end
      end
      @@matches_hash[current_user.id] = @matches_arr
  end


  def is_mentee()
    @mentee = Mentee.find_by(user_id: current_user.id)
    @mentors.each do |mentor|
      if current_user.id != mentor.user_id
        if (@common_subjects_map[@mentee.major]) != nil
          if (mentor.length_of_mentorship==@mentee.length_of_mentorship) or (@common_subjects_map[@mentee.major].include? mentor.current_position)
            @newMatch= Match.new(:user_id => current_user.id, :mentor_id => mentor.id, :mentee_id => @mentee.id, :accepted => false, :rejected => false)
            check_duplicate(1)
          end
        else
          if (mentor.length_of_mentorship==@mentee.length_of_mentorship)
            @newMatch= Match.new(:user_id => current_user.id, :mentor_id => mentor.id, :mentee_id => @mentee.id, :accepted => false, :rejected => false)
            check_duplicate(1)
          end
        end
      end
    end
    @@matches_hash[current_user.id] = @matches_arr
  end
  
  # POST /matches or /mentors.json
  def create
    @mentors = Mentor.all
    @mentees= Mentee.all 
    @all_matches = Match.all
    @first_match = Match.new()
    @common_subjects_map=JobMap.new.map_method
    @matches_arr=[]
    if current_user.mentor 
      is_mentor()
    else
      is_mentee()
    end
    @created = true
    @user = current_user
    @user_matches = Match.where(user_id: current_user.id, accepted: false, rejected:false)
    @user_match = nil

    redirect_to '/matches'    #redirect to index
  end
  
  def set_match
  end

  # Only allow a list of trusted parameters through.
  def mentor_params

  end

  def show
  end

end

app/helpers/matches_helper.rb
module MatchesHelper
    include CableReady::Broadcaster

    def update_match(user_id, othermatch)
        cable_ready["accepted"].set_value(
            selector: "#"+ ActionView::RecordIdentifier.dom_id(othermatch),
            name: "accepted",
            value: true
            # html: ApplicationController.render(othermatch),
            # detail: {
            #     id: match_id,
            #     to_user: User.find_by(id:user_id),
            #     #other_match: Match.find_by(id: match_id),
            #     notif_type: "match"
            # }
        )
        cable_ready.broadcast
        cable_ready["accepted"].set_style(
            selector: "#"+ ActionView::RecordIdentifier.dom_id(othermatch),
            name: "background",
            value: "red"
            # html: ApplicationController.render(othermatch),
            # detail: {
            #     id: match_id,
            #     to_user: User.find_by(id:user_id),
            #     #other_match: Match.find_by(id: match_id),
            #     notif_type: "match"
            # }
        )
        cable_ready.broadcast
        cable_ready["accepted"].set_property(
            selector: "#"+ ActionView::RecordIdentifier.dom_id(othermatch),
            name: "accepted",
            value: true
            # html: ApplicationController.render(othermatch),
            # detail: {
            #     id: match_id,
            #     to_user: User.find_by(id:user_id),
            #     #other_match: Match.find_by(id: match_id),
            #     notif_type: "match"
            # }
        )
        cable_ready.broadcast
        # cable_ready["accepted"].morph(
        #     selector: "#" + ActionView::RecordIdentifier.dom_id(othermatch),
        #     html: ApplicationController.render(othermatch)
        #   )
        #   cable_ready.broadcast
    end
end

app/views/matches/home.html.erb
<p id="notice"><%= notice %></p>

<head>
    <title>Mentorship App</title>
    <meta charset="utf-8">
</head>
<body>
    <link href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet" />
    <script src="js/vendor/modernizr-2.7.1.min.js"></script>  
    <% if logged_in? %>
      <% accepted_matches_for_user = current_user.get_accepted_matches() %>
      <% if accepted_matches_for_user.length == 0 %>
          <div class= "center jumbotron" style="background:white" >
            <h1>Hi, <%= current_user.firstname %>!</h1>
            <br>
            <% if @matches_for_user.key?(current_user.id) %>
              <h2>It looks like you haven't matched with anyone yet, click the button below to explore possible matches.</h2>
              <button class="button2"><%= link_to 'Explore', explore_path %></button>
            <% else %>
              <h2>Click the button below to generate possible matches to explore based on your interests.</h2>
              <div class = "match_creation">
                <%= form_tag matches_create_path, method: :post, id: 'match_creation_form'  do %>
                  <%= submit_tag 'Make matches', data: { disable_with: "Please wait..." }, class: "button2"%>
                </div>
              <% end %>
            <%end%>
          </div>
      <% else %>
          <div class = "center jumbotron" style="background-color:white;font-size:80px;">
              <%= link_to "Explore", explore_path, class: "r-link ai-element ai-element3"%> 
              <br>
              <%= link_to "", "/users/new", class: "r-link ai-element ai-element3"  %>
              <% @mentee = Mentee.find_by(user_id: current_user.id) %>
              <% @mentor = Mentor.find_by(user_id: current_user.id) %>
              <% if @mentee.nil? && @mentor.nil?%>
                  <%= link_to "Log out", logout_path, method: :delete, class: "r-link ai-element ai-element3" %>
              <% elsif current_user.mentee? %>
                  <%= link_to "Profile", menteeprofile_path(@mentee), method: :get, class: "r-link ai-element ai-element3"%>
                  <% elsif current_user.mentor? %>
                  <%= link_to "Profile", mentorprofile_path(@mentor), method: :get, class: "r-link ai-element ai-element3" %>
                  <% else %>
                  <%= link_to "Profile", userprofile_path(current_user), method: :get, class: "r-link ai-element ai-element3" %>
              <% end %>
              <br>
              <%= link_to "Matches", matches_path, method: :get, class: "r-link ai-element ai-element3" %>
              <br>
              <%= link_to "Log out", logout_path, method: :delete, class: "r-link ai-element ai-element3" %>
          </div>
        <% end %>   
      <% else %>
          <div class="parallax"></div>

        <div style="height:1000px;background-color:white;font-size:50px;background-size: auto;max-height: 650px;">
            <br>
            <%= link_to "Log in", login_path, class: "r-link ai-element ai-element__label ai-element3"%>
            <br>
            <%= link_to "Sign up", "/users/new", class: "r-link ai-element ai-element__label ai-element3" %>
        </div>
      <%end %>
</body>

app/views/matches/index.html.erb
<p id="notice"><%= notice %></p>

<head>
    <title>Mentorship App</title>
    <meta charset="utf-8">
    <script src="//ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.7/js/bootstrap.min.js"></script>
</head>

<body>

    <% accepted_matches_for_user = current_user.get_accepted_matches() %>
    
    <% if accepted_matches_for_user.length > 0 %>
    <h1>Matches</h1>
        <div class= "container" style="background:white" >
            <div id="myCarousel" class="carousel slide" data-ride="carousel" data-interval="false" >
                    <!-- Indicators -->
                <ol class="carousel-indicators">
                    <% accepted_matches_for_user.each_with_index do |possible_match, i| %>
                    <li data-target="#mycarousel" data-slide-to=#{i) class="#{'active' if i == 0}"></li>
                    <% end %>
                </ol>

                <!-- Wrapper for slides -->
                <div class="carousel-inner" role="listbox">
                    <% accepted_matches_for_user.each_with_index do |match, i| %>
                    <% if current_user.mentee? %>
                        <% mentor_record = Mentor.find_by(id: match.mentor_id) %>
                        <% user_record = mentor_record%>
                        <% user = User.find(mentor_record.user_id) %>
                    <%else %>
                        <% mentee_record = Mentee.find_by(id: match.mentee_id)%>
                        <% user_record = mentee_record%>
                        <% user = User.find(mentee_record.user_id) %>
                    <%end%>
                        <div class="item <%= "active " if i==0 %>">
                            <div>    
                            <div class="container flip-card">
                                <div class="flip-card-inner">
                                    <div class="flip-card-front center">
                                        <% if user.avatar.attached? %>
                                            <img class="card-img-top" src="<%=(url_for(user.avatar))%>" width="300" height="300">
                                        <% else %>
                                            <img class="card-img-top" src="https://www.pngitem.com/pimgs/m/30-307416_profile-icon-png-image-free-download-searchpng-employee.png" width="300" height="300"/>
                                        <% end %>
                                        <h1 class="card-title"><%= user.firstname + " " + user.lastname %></h1>
                                        <h2 class="card-text text-muted"><%= user.email %></h2>
                                        <h3 class="card-text text-muted">**Hover over me**</h3>
                                    </div>
                                    <div class="flip-card-back">
                                        <div class="center" style="padding:60px">
                                            <% if current_user.mentor? %>
                                                <div>
                                                    <table class= "table">
                                                        <tbody>
                                                        <tr>
                                                        <td>Major</td>
                                                        <td><%= mentee_record.major %></td>
                                                        </tr>
                                                        <tr>
                                                        <td>Areas of Interest</td>
                                                        <td><%= mentee_record.area_of_interest%></td>
                                                        </tr>
                                                        <td>Location</td>
                                                        <td><%= mentee_record.location%></td>
                                                        </tr>
                                                        <td>Graduation Year</td>
                                                        <td><%= mentee_record.graduation_year%></td>
                                                        </tr>
                                                        </tbody>
                                                    </table>
                                                </div>
                                                <% other_user_id = mentee_record.user_id%>
                                                <% search_record = Mentor.find_by(user_id: @user.id) %>
                                                <% other_match = Match.find_by(user_id: other_user_id, mentor_id: search_record.id) %>
                                            <%else %>
                                                <div>
                                                    <table class= "table">
                                                        <tbody>
                                                        <tr>
                                                        <td>Area of expertise</td>
                                                        <td><%= mentor_record.area_of_expertise %></td>
                                                        </tr>
                                                        <tr>
                                                        <td>Preferred Method of Contact</td>
                                                        <td><%= mentor_record.preferred_method_of_contact %></td>
                                                        </tr>
                                                        <tr>
                                                        <td>Alma Matter</td>
                                                        <td><%= mentor_record.school %></td>
                                                        </tr>
                                                        <td>Current Position</td>
                                                        <td><%= mentor_record.current_position%></td>
                                                        </tr>
                                                        <td>Location</td>
                                                        <td><%= mentor_record.location%></td>
                                                        </tr>
                                                        </tr>
                                                        <td>Preferred Length of Mentorship</td>
                                                        <td><%= mentor_record.length_of_mentorship%></td>
                                                        </tr>
                                                        </tbody>
                                                    </table>
                                                </div>
                                                <% other_user_id = mentor_record.user_id%>
                                                <% search_record = Mentee.find_by(user_id: @user.id) %>
                                                <% other_match = Match.find_by(user_id: other_user_id, mentee_id: search_record.id) %>
                                            <% end %>                                 

                            <%if other_match != nil %>
                                <%if other_match.accepted %> 
                                    Status: It's a match! You can now chat with this user
                                    <br>

                                     <%= link_to "Chat", room_create_path(room: { name: "#{user.firstname} #{user.lastname} and #{current_user.firstname} #{current_user.lastname}"}), method: :post, class: "button3"%>
                                <% elsif other_match.rejected %>
                                    Status: Match rejected :(. Swipe to see other matches or explore for more!
                                    <%  @match_to_reject = Match.find_by(user_id: @user.id, mentor_id: @temp_id, mentee_id: mentee_record.id)  %>
                                    <%= form_tag welcome_reject_path, method: :post, class: "form" do %>
                                        <%= hidden_field_tag :match_id, @match_to_reject.id %>
                                        <%= submit_tag 'Reject Match', class: "btn-red-qa"%>
                                    <% end %>      
                                <% else%>
                                    Status: Match pending acceptance
                                <%end%>
                            <%end%>
                                        </div>
                                    </div>
                                </div>
                            </div>                        
                            </div>
                        </div>
                    <% end %>
                </div>
                <a class="left carousel-control" href="#myCarousel" data-slide="prev" style="background:white;color:#003478">
                    <span class="icon-prev"></span>
                </a>
                <a class="right carousel-control" href="#myCarousel" data-slide="next" style="background:white;color:#003478">
                    <span class="icon-next"></span>
                </a>
            </div>
        </div>
    <% else %>
        <h1> Click the button below to explore matches </h1>
        <div class="center"><%= link_to "Explore", explore_path, method: :get, class: "button2" %> </div>
    <% end %>
</table>
</body>

<br>