config/routes.rb
Rails.application.routes.draw do
  resources :messages
  resources :rooms
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  resources :matches
  resources :mentees
  resources :mentors
  resources :users
  resources :states, only: :index
  root 'matches#home'
  get '/room', to: 'rooms#index'
  post 'room/create', to: 'rooms#create'
  get  '/signup',  to: 'users#new'
  get  '/channelshow',  to: 'channnel_users#show'
  post 'channel_users/create'
  get  '/home',  to: 'matches#home'
  get '/menteeprofile/:id', to: 'mentees#show', as: 'menteeprofile'
  get '/mentorprofile/:id', to: 'mentors#show', as: 'mentorprofile'
  get '/userprofile/:id', to: 'users#show', as: 'userprofile'
  get    '/login',   to: 'sessions#new'
  get    '/explore',   to: 'welcome#show'
  get     '/additional-info', to: 'users#additional_info'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  post 'matches/create'
  post 'welcome/accept', to: 'welcome#accept'  #for rejecting matches
  post 'welcome/reject', to: 'welcome#reject'    #for accepting matches
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/layouts/_footer.html.erb
<footer class="footer">
</footer>

app/views/layouts/_header.html.erb
<nav class="navbar bg-transparent navbar-expand-lg navbar-fixed-top">
      <div class="container">
      <% if logged_in? %>
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target=".navbar-collapse" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand"><%= link_to image_tag("logo1.png", size: "150x150", alt: "logo"), home_path, class: 'nav navbar-brand navbar-left', id: 'logo' %></a>
        </div>
        <div id="navbar" class="collapse navbar-collapse">
            <ul class="nav navbar-nav navbar-right">
            <% @mentee = Mentee.find_by(user_id: current_user.id) %>
            <% @mentor = Mentor.find_by(user_id: current_user.id) %>
            <li><%= link_to "Chat", rooms_path, method: :get, class: "r-link ai-element ai-element3" %></li> 
            <% if @mentee.nil? && @mentor.nil?%>
              <li><%= link_to "Log out", logout_path, method: :delete, class: "r-link ai-element ai-element3" %></li> 
            <% elsif current_user.mentee? %>
              <li><%= link_to "Explore", explore_path, method: :get, class: "r-link ai-element ai-element3"%></li> 
              <li><%= link_to "Profile", menteeprofile_path(@mentee), method: :get, class: "r-link ai-element ai-element3" %></li> 
              <li><%= link_to "Matches", matches_path, method: :get, class: "r-link ai-element ai-element3" %></li> 
              <li><%= link_to "Log out", logout_path, method: :delete, class: "r-link ai-element ai-element3" %></li> 
            <% elsif current_user.mentor? %>
              <li><%= link_to "Explore", explore_path, method: :get, class: "r-link ai-element ai-element3" %></li> 
              <li><%= link_to "Profile", mentorprofile_path(@mentor), method: :get, class: "r-link ai-element ai-element3" %></li> 
              <li><%= link_to "Matches", matches_path, method: :get, class: "r-link ai-element ai-element3" %></li> 
              <li><%= link_to "Log out", logout_path, method: :delete, class: "r-link ai-element ai-element3" %></li> 
            <% else %>
              <li><%= link_to "Explore", explore_path, method: :get, class: "r-link ai-element ai-element3" %></li> 
              <li><%= link_to "Profile", userprofile_path(current_user), method: :get, class: "r-link ai-element ai-element3" %></li> 
              <li><%= link_to "Matches", matches_path, method: :get, class: "r-link ai-element ai-element3" %></li> 
              <li><%= link_to "Profile", profile_path, method: :get, class: "r-link ai-element ai-element3" %></li> 
              <li><%= link_to "Log out", logout_path, method: :delete, class: "r-link ai-element ai-element3" %></li> 

              <% end %>
            </ul>
        </div><!--/.nav-collapse -->
        <% end %>
      </div>
    </nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
  <%= render 'layouts/header' %>
    <title>Mentorship</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <script src = "https://code.jquery.com/jquery-3.1.1.slim.min.js" integrity = "sha384-A7FZj7v+d/sdmMqp/nOQwliLvUsJfDHW+k9Omg/a/EheAdgtzNs3hpfag6Ed950n"
crossorigin = "anonymous"> </script> 
<script src = "https://cdnjs.cloudflare.com/ajax/libs/tether/1.4.0/js/tether.min.js"
integrity = "sha384-DztdAPBWPRXSA/3eYEEUWrWCy7G5KFbe8fFjk5JAIxUYHKkDx6Qin1DkWx51bBrb"
crossorigin = "anonymous"> </script> 
<script src = "https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/js/bootstrap.min.js"
integrity = "sha384-vBWWzlZJ8ea9aCX4pEW3rVHjgjt7zpkNpZk+02D9phzyeVkE+jo0ieGizqPLForn"
crossorigin = "anonymous"> </script>
    <div class="container">
      <%= yield %>
      <%= render 'layouts/footer' %>
    </div>
  </body>
</html>